<h1>Notes</h1>

<p>
There are some things that don't really fit in a blog because I want to keep them updateable,
while editing a blog post seems somewhat wrong. I'll keep them in this section.
</p>

<h2>On the world wide web</h2>
<dl>
  <dt><a href="/notes/powered-by">&ldquo;Powered by...&rdquo;, or the phenomenon of web software buttons</a></dt>
  <dd>A note on the once common buttons that promoted web server or client software</dd>
  <dt><a href="/notes/mobile-friendly">Old webmaster's guide to mobile-friendly websites</a></dt>
  <dd>A passive-aggressive guide to adapting old websites for mobile audience.</dd>
  <dt>An introduction to <a href="/notes/ssg">static website generators</a>.</dt>
</dl>

<h2>On programming languages</h2>
<dl>
  <dt><a href="/notes/zen-of-ada/">Zen of Ada</a></dt>
  <dd>A comparison of Zen of Python with the Steelman requirements (the Ada design document).</dd>
</dl>

<h2>On security</h2>
<dl>
  <dt><a href="/notes/signing-parties">Key signing parties considered useless</a></dt>
  <dd>A note on key signing parties as a form of security theater.</dd>
</dl>

<h2>On software development in general</h2>
<dl>
  <dt><a href="/notes/easter-eggs">On “easter eggs”</a></dt>
  <dd>A proposal for a sensible easter egg policy without the extremes of either &ldquo;trustworthy computing&rdquo; or flight simulators inside spreadsheet programs.</dd>
  <dt><a href="/notes/intuitive">Intuitive and revolutionary</a><dt>
  <dd>Still much ignored fact that nothing is inherently intuitive.</dd>
</dl>

<h2>On human languages</h2>
<dl>
  <dt><a href="/notes/irish-mutations">Irish initial mutations</a></dt>
  <dd>An attempt to present Irish initial mutations groups by place of articulation to make their patterns more clearly visible.</dd>
  <dt><a href="/notes/irish-article">Old and Modern Irish definite article</a></dt>
  <dd>A side-by-side comparison of definite article forms in Old Irish and Modern Irish.</dd>
</dl>
