<h1>Notes</h1>

<p>
There are some things that don't really fit in a blog because I want to keep them updateable,
while editing a blog post seems somewhat wrong. I'll keep them in this section.
</p>

<ul class="nav">
   <li class="nav"> A proposal for an <a href="/notes/easter-eggs">easter egg policy</a> that you can use for your software project. </li>
   <li class="nav"> A note on the usefulness of <a href="/notes/signing-parties">key signing parties</a> and the nature of trust. </li>
   <li class="nav"> A <a href="/notes/zen-of-ada/">comparison</a> of the Zen of Python with the Steelman requirements (the Ada design document). </li>
</ul>

