<h1>Intuitive and revolutionary</h1>


<p>
There's a notion that intuitive is good and unintuitive is bad. For some definitions of good and bad, that is true.
Things that are intuitive for their target audience are easier to explain and market and have a better chance to catch on.
But if something is not intuitive, is it necessarily bad?
</p>
<p>
The funny thing is that very few things are intuitive for everyone. Almost everything that is now intuitive, at some point in history,
was weird and hard to explain. Positional number systems only became the standard in the Middle Ages—yes, people actually used roman numerals
for non-decorative purposes before that. The concept of variables and equations is even newer—lack of that concept was seriously holding
mathematics back.
</p>
<p>
Even in recent history, many inventions that are now obvious used to require explanation and training. There were lots of books that explained the
<a href="https://en.wikipedia.org/wiki/WIMP_(computing)">WIMP</a> (windows, icons, menus, pointer) paradigm to users.
Some may argue that GUI is inherently more intuitive than CLI, but the fact remains, far from everyone could just sit at the computer running a GUI
program for the first time and start using it fluently right away. 
</p>
<p>
The reason GUI may be more inherently intuitive is that it builds upon concepts people were already familiar with: file cabinets, trash cans and so on.
To explain new things, we turn to metaphors. A typical description of a new program or service may sound like &ldquo;Pastebin for traffic dumps&rdquo;,
&ldquo;Instagram for musicians&rdquo;, or &ldquo;Pornhub for Haskell programmers&rdquo;. It's pretty obvious now what they may look like (with the exception
of the last one perhaps) because everyone already knows what Pastebin or Instagram are.
</p>
<p>
There are categories of people for whom traffic dumps or Pastebin are not quite intuitive though. Something is intuitive if it's <em>just</em> outside
of your existing experience.
</p>
<p>
This brings us to the point that intuitive and revolutionary are often contradictory properties. A good invention allows people to do
things they couldn't do before. It may require revolutionary internals, like wireless phones, but in the end, &ldquo;I wish I could talk with anyone
at any distance&rdquo; was a common idea long before it was possible. The best ones allow people to do things no one thought of before.
</p>
<p>
An old joke goes &ldquo;computers can solve all problems that didn't exist before computers were invented&rdquo;. A fun thing is that Charles Babbage himself
only thought of a narrow class of problems and he thought programming would be simply translating formulas to punched card. It was Ada Lovelace who realized
that you can encode any information in digital form and use a programmable computer for tasks far beyond numerical computations. No one before thought
that automatically searching and analyzing textual information was a possibility, for example.
</p>
<p>
We still see it with regular expressions. While ability to search for exact words is intuitive for all computer users, regular expressions are still intuitive
only for people familiar with automata and formal languages, even though they could help many people with their daily tasks. People are often impressed when
they see it in action, but it's hard to teach because it's completely outside of their prior experience.
</p>
<p>
So, if something is not intuitive, it may be poorly designed, but many incredibly powerful ideas are not intuitive just because there is no analogy for them yet.
Dismissing those ideas just for that reason would be counteproductive.
</p>
<p>
And regarding &ldquo;if you can't explain it to a six year old...&rdquo;, try to explain birth control to them.
</p>
