{% set date 2018 December 30 %}

<h1>&ldquo;Powered by...&rdquo;, or the phenomenon of web software buttons</h1>

<p>
Most web banners/buttons were meant to promote websites, sometimes as a part of banner exchange,
sometimes as a paid advertisment, and sometimes people would place banners of their favorite
websites without demanding anything from them, just to help everyone else discover those websites.
</p>
<p>
But there was also a curious kind of buttons meant to promote web client and server software, rather than websites.
That alone sets them apart from all other banners, but there were other characteristic features that made them
a rather unique phenomenon.
</p>
<p>
First, people would always use them voluntarily just because they liked and used the software, without expecting anything
in return.
Second, they are relics of the era when the World Wide Web was a medium of its own with visible inner workings, rather than
the luminiferous aether permeating the entire Internet it is now. Last but not least, buttons promoting web server software
developed a recognizeable format, often using the titular &ldquo;powered by...&rdquo; phrase, and become a visible part of the
geek culture for some time.
</p>

<h2>Web browser buttons</h2>

<p>
I believe web browser buttons predate buttons that promote web server software, though I have no reliable data
to prove it. The &ldquo;Netscape Now!&rdquo; button might have been the one that created the trend, and popularized
the 80x31 pixel format.
</p>

<img src="/images/powered-by/netscape_now.gif" alt="Netscape Now button"/>
<img src="/images/powered-by/ie.gif" alt="Internet Explorer button"/>

<p>
A lot of time people put them on their pages not just to tell everyone about their favorite web browser,
but also to indicate the browser it's best viewed with, and give people a download link
</p>
<p>
In this light, what's more interesting to me is spoofs and parodies created by proponents of cross-browser markup.
</p>

<img src="/images/powered-by/anybrowser.gif" alt="Any browser button" />
<img src="/images/powered-by/any_browser_01.png" alt="Any browser button, variant 2" />
<img src="/images/powered-by/any_browser_any_os.png" alt="Any browser, any OS button" /> 
<img src="/images/powered-by/nogluck.gif" alt="No markup glitches in any browser" title="No [markup] glitches in any browser" />
<img src="/images/powered-by/best_viewed_with_eyes.jpg" alt="Best viewed with eyes button" />

<p>
Later web browser buttons have still seen some benign use for browser advocacy.
</p>

<img src="/images/powered-by/get_firefox_01.gif" alt="Get Firefox button" />
<img src="/images/powered-by/get_firefox_02.png" alt="Get Firefox button" />
<img src="/images/powered-by/firefox_36.png" alt="Firefox 3.6 button" />

<p>
Even those got their own friendly parodies though, like this button by <a href="https://gkn.me.uk/firefoxmiscellanea/">Greg Nicholson</a>.
</p>
<img src="/images/powered-by/get_drunk.png" alt="Get drunk button" />

<h2>&ldquo;Powered by...&rdquo; server software buttons</h2>

<p>
The other kind of buttons is the buttons that tell the visitor about the web server software.
</p>
<p>
This is a more interesting phenomenon to me. Web browser choice is up to the visitors,
they may choose to use the one some webmaster loves most or not, so a web browser button is a call to action.
</p>
<p>
Server software buttons, however, are pure statements. A visitor cannot use that information in any way when
it comes to the website they are visiting. An average visitor, even an average webmaster of the shared hosting era,
could not benefit from that information in any way at all.
<p>
Yet they existed and were very common on websites of
individual geeks, open source projects, and small software companies. 
Not quite surprising, since those are the websites made by people who care about the web server software,
and that are likely to have visitors who understand what on earth it all means.
<p>
During my archeological expedition,
I've found two examples of such pages that are still online at the time of writing and reveal their entire web server stack in a gallery
of buttons at the bottom: the home page of <a href="http://kjdtech.com/">Kevin J. D'Aquila</a> and the website
of the <a href="http://www.rx3.org/">Rx3 team</a>. Generally, those &ldquo;powered by&rdquo;
images are rather hard to find these days, and I had to harvest most of them from archived pages.
</p>
<img src="/images/powered-by/buttons.png" alt="Powered by buttons on a website" />
<p>
I think there are a few reasons why people used them. The first reason is, as usual, bragging rights.
As <a href="http://drx.a-blast.org/~drx/index.en.html">Dragan Espenschied</a> said
(according to <a href="http://art.teleportacia.org/observation/vernacular/tilde.html">Olia Lialina</a>),
the tilde in his URL is a silent indicator of his knowledge of server software, as well as an indicator
of his relationship with the web server and its community.
</p>
<p>
These days many hosting providers allow you to create a website with your own domain pointing to it in a few clicks, with zero knowledge of the
underlying protocols and software; but to setup a home page with a tilde in its URL you need to know
how to setup your own web server and configure <a href="https://httpd.apache.org/docs/2.4/mod/mod_userdir.html">mod_userdir</a>
or equivalent. Back in the days it was the other way around, to get a home page with a tilde you would just drop some files
in a directory, but making a website with your own domain required knowledge of the web server software and at least a cursory knowledge of DNS.
People who could do it (myself included) would hardly miss a chance to show off.
</p>

<p>
I believe open source advocacy was another, maybe even bigger reason. Those buttons almost invariably promote open source software.
I don't think I've ever seen a &ldquo;Powered by Microsoft IIS&rdquo; button. Absense of &ldquo;Powered by Solaris&rdquo; or 
&ldquo;Powered by OpenVMS&rdquo; buttons may be explained by the price of the hardware and licenses, which only companies that would never
put any such buttons on their website could afford. People happily promoted proprietary web browsers, but somehow promoting web server
software mostly happened in the realm of open source.
</p>
<p>
People running proprietary software might not feel any need to promote it, but at the time when free and open source software
was still struggling to gain mainstream acceptance in any area, its users and advocates definitely felt a need to promote it
and show that it's a valid choice.
</p>

<h3>Web server buttons</h3>

<p>
An interesting fact is that &ldquo;Powered by Apache&rdquo; buttons have been popular even when Apache HTTPD was already the
most popular web server, and, for a time, essentially <em>the</em> web server.
</p>

<img src="/images/powered-by/apache_powered_01.gif" alt="Powered by Apache, variant 1" />
<img src="/images/powered-by/apache_powered_02.png" alt="Powered by Apache, variant 2" />
<img src="/images/powered-by/apache_powered_03.gif" alt="Powered by Apache, variant 3" />

<p>
My guess is that it wasn't about promoting Apache HTTPD as such, but about promoting open source software in general.
The web was the first part of the information technology world where open source software rose to a dominant position,
so it might have been like saying that if the web runs on open source, there's no reason everything else can't.
While it might have been the subconscious thought, I think many people added that button just for the sake of completeness
though.
</p>

<h3>Operating system buttons</h3>

<p>
The operating system and distribution debate never ends though, and people engage in advocacy in every possible way,
including web buttons.
</p>
<p>
Many OSes and distributions designed official buttons, and some of them, including Debian, FreeBSD, NetBSD and some others
still make them available on their website, even well after the popularity of such buttons waned.
</p>

<img src="/images/powered-by/linux_powered_01.png" alt="Linux powered" />
<img src="/images/powered-by/linuxnow.gif" alt="Linux Now!" />
<img src="/images/powered-by/debian_powered_01.png" alt="Debian Powered, variant 1" />
<img src="/images/powered-by/debian_powered_02.gif" alt="Debian Powered, variant 2" />
<img src="/images/powered-by/redhat_powered_01.gif" alt="RedHat Powered" />
<img src="/images/powered-by/powered_by_asplinux_00.png" alt="ASPLinux powered" />
<img src="/images/powered-by/fedora_powered_00.png" alt="Fedora Powered, variant 1" />
<img src="/images/powered-by/fedora_powered_01.png" alt="Fedora Powered, variant 2" />
<img src="/images/powered-by/mandriva_powered.png" alt="Mandriva Powered" />
<img src="/images/powered-by/slackware_powered_00.gif" alt="Slackware powered, variant 1" />
<img src="/images/powered-by/slackware_powered_01.gif" alt="Slackware powered, variant 2" />
<img src="/images/powered-by/slackware_powered_02.gif" alt="Slackware powered, variant 3" />
<img src="/images/powered-by/slackware_apache.png" alt="Slackware and Apache powered" />
<img src="/images/powered-by/freebsd_00.gif" alt="FreeBSD Powered, variant 1" />
<img src="/images/powered-by/freebsd_powered_00.gif" alt="FreeBSD Powered, variant 2" />
<img src="/images/powered-by/freebsd_powered_01.gif" alt="FreeBSD Powered, variant 3" />
<img src="/images/powered-by/openbsd_powered_00.png" alt="OpenBSD Powered, variant 1" />
<img src="/images/powered-by/netbsd_powered_01.png" alt="NetBSD Powered, variant 1" />
<img src="/images/powered-by/netbsd_powered.png" alt="NetBSD Powered, variant 2" />

<p>
While most of OSes promoted with web buttons I've seen are open source, there
are a few examples of proprietary OS buttons:
</p>

<img src="/images/powered-by/darwin_powered.png" alt="Darwin Powered" />
<img src="/images/powered-by/ecomstation_powered.png" alt="eComStation Powered" />

<h3>Programming languages and databases</h3>

<p>
At the end of the web 1.0 era, making static websites was no longer cool, and people started to generate
pages dynamically even if their content didn't change any often.
People tend to have even stronger opinions about programming languages than operating systems,
which was definitely reflected in promotional buttons.
</p>
<p>
Relational database software was never excluded from the debate, and the buttons either.
MySQL and Firebird still provide official buttons on their websites. Even more curiously,
MariaDB, which is a relatively recent fork of MySQL, continued the tradition and made new
official buttons, even though I'm still to see anyone use them.
</p>

<img src="/images/powered-by/perl_powered_01.gif" alt="Perl Powered, variant 1" />
<img src="/images/powered-by/perl_powered_02.gif" alt="Perl Powered, variant 2" />
<img src="/images/powered-by/perl_powered_03.png" alt="Perl Powered, variant 3" />
<img src="/images/powered-by/php_00.png" alt="PHP Powered, variant 1" />
<img src="/images/powered-by/php3.png" alt="PHP Powered, variant 2" />
<img src="/images/powered-by/php_powered_01.png" alt="PHP Powered, variant 3" />
<img src="/images/powered-by/parser01.gif" alt="Parser Powered, variant 1" />
<img src="/images/powered-by/parser02.gif" alt="Parser Powered, variant 2" />
<img src="/images/powered-by/mysql_powered.png" alt="MySQL Powered" />
<img src="/images/powered-by/mariadb_powered.png" alt="MariaDB Powered" />
<img src="/images/powered-by/postgresql_powered.png" alt="MySQL Powered" />
<img src="/images/powered-by/firebird_powered.png" alt="Firebird Powered" />

<p>
I find it interesting that less common languages are also more rarely promoted with buttons.
It would seen reasonable that their users would feel a stronger need to promote them,
but apparently it wasn't the case. There are few &ldquo;Powered by Python&rdquo; buttons
and even fewer &ldquo;Powered by Ruby&rdquo;, not even mentioning ML, Haskell, or Common Lisp.
Judging by myself, it may be that their users prefer more active advocacy than simply placing
a button on their pages.
</p>
<p>
Python and Ruby became common web languages after this kind of buttons lost its popularity in the
web 2.0 era, though some buttons for them did exist. <a href="https://www.parser.ru/">Parser</a>
is a rare example of an obscure language with a button.
</p>

<h3>Hardware</h3>

<p>
Buttons that promote server or development workstation hardware are relatively rare, but there
are some examples.
</p>

<img src="/images/powered-by/amd_powered.gif" alt="AMD Powered" />
<img src="/images/powered-by/created_with_amiga.gif" alt="Created with Amiga" />
<img src="/images/powered-by/hosted_on_macintosh.gif" alt="Hosted on Macintosh" />

<p>I've seen at least one spoof though.</p>
<img src="/images/powered-by/220_volt_powered.jpg" alt="Powered by 220V" />

<h3>Editors</h3>

<p>
Using visual HTML editors such a Microsoft Frontpage, or worse, exporting
HTML from word processors, was common, but it wasn't something to be proud of,
and the unreadable tag soup they created was shunned by professionals and
amateurs who cared about maintainability alike. There does exist
a Frontpage button, but who in their right mind would put in on their page?
</p>
<p>
As a protest against visual editors, many people did use a button of their
favorite editor. One odd example is relatively common &ldquo;made with notepad&rdquo;
button. Why anyone would use an editor that doesn't even have keyword highlighting?
Among <em>real</em> text editors, ViM seems most commonly mentioned.
Emacs buttons are much less common, and I've found a possibly unique example
of a GNU nano button.
</p>

<img src="/images/powered-by/frontpage.gif" alt="Frontpage" />
<img src="/images/powered-by/notepad.gif" alt="Notepad" />
<img src="/images/powered-by/vi.png" alt="Vim powered, variant 1" />
<img src="/images/powered-by/vim_powered.gif" alt="Vim powered, variant 2" />
<img src="/images/powered-by/vim_powered_02.png" alt="Vim powered, variant 3" />
<img src="/images/powered-by/emacs_powered_00.png" alt="Emacs powered" />
<img src="/images/powered-by/made_with_nano.png" alt="Made with nano" />

<h3>Static generators</h3>

<p>
Static website generators are older than one may think, and Jekyll wasn't the first one.
I found two buttons, one for the <a href="http://template-toolkit.org/">Template Toolkit</a>,
another one for the now defunct Website Meta Language that used to be hosted at thewml.org
</p>


<img src="/images/powered-by/wml_powered.png" alt="WML powered" />
<img src="/images/powered-by/template_toolkit_powered.gif" alt="Template toolkit powered" />

<h2>The rise and fall of web software buttons</h2>

<p>
It's hard to tell when those buttons completely fell out of fashion, but I think it was
in the first few years of the web 2.0 era. One possible reason is that at the time when large
scale attacks became common, revealing anything about your software stack seemed like a bad idea,
and people started reconfiguring their servers to hide anything that could help attackers find
an attack vector.
</p>
<p>
If we assume that promoting open source software was one of the most important reasons,
perhaps the fact that the web backend standardized on open source software also played a role,
there wasn't so much need for advocacy anymore.
</p>
<p>
Or maybe it's just changing fashions. Regardless, we can hardly see those buttons on new
websites, for better or worse, and they remain a characteristic feature of a past era.
</p>

<h2>Copyright notice</h2>

<p>
All copyrights and trademarks belong to their respective owners. In some cases, such as with FreeBSD and NetBSD buttons,
the license explicitly states they are to be used only on web servers running the OS in question, which is not the case with my server.
I believe using these images to illustrate an article is fair use in the copyright sense of those words.
If you are a copyright or trademark owner and you think I'm infringing your rights, feel free to contact me.
</p>
<p>
Then again, at the time when most of those images were made, people used to take and reuse images from someone else's website
without hesitation.
</p>

<h2>Last but not least...</h2>

<p>This page would not be complete without buttons for this very website:</p>

<img src="/images/powered-by/fedora_powered_03.png" alt="Fedora Powered, variant 3" />
<img src="/images/powered-by/apache_powered_03.gif" alt="Powered by Apache, variant 3" />
<img src="/images/powered-by/ocaml.png" alt="OCaml" width="150px" />
