{% set date 2015 June 10 %}

<p>
I'm <strong> Daniil Baturin</strong>, also known as <strong>dmbaturin</strong>.
I pronounce it as <em>Dah-n-i-i-l Bah-too-rin</em>, but it's up to you how
to pronounce it. It's nice to have a name with a simple ASCII representation anyway.
</p>
<p>I write programs and build networks. Sometimes those programs have something to do with networks,
   sometimes they don't.</p>

<p>You can also find me in other places:</p>
<ul>
  <li> Github: <a href="http://github.com/dmbaturin">github.com/dmbaturin</a> </li>
  <li> Blog: <a href="http://stuff.baturin.org">stuff.baturin.org</a> </li>
  <li> Twitter: <a href="http://twitter.com/dmbaturin">@dmbaturin</a> </li>
  <li> dmbaturin on <a href="http://freenode.net">Freenode</a> and <a href="http://esper.net">Esper</a>
       IRC networks.</li>
</ul>

<p>You can contact me by email &lt;daniil (at) baturin (dot) org&gt;
(use <a href="http://pool.sks-keyservers.net:11371/pks/lookup?op=vindex&amp;search=0x4726DF9511E0AF1F">PGP key</a>
if you wish).</p>
