{% set date 2016 Septermber 02 %}

<p>
I'm <strong> Daniil Baturin</strong>. On the Internet I usually go by <strong>dmbaturin</strong>,
the &ldquo;m&rdquo; is from the middle name, of sorts.
I pronounce it <em>Dah-n-i-i-l Bah-too-rin</em>, but it's up to you how
to pronounce it. It's nice to have a name with a simple ASCII representation anyway.
</p>
<p>I write programs and build networks. Sometimes those programs have something to do with networks,
   sometimes they don't.</p>
<p>You may know me as one of the maintainers of <a href="http://vyos.io">VyOS</a> network operating system,
   my biggest and most important project at this time.</p>

<p>You may be interested in my <a href="/projects">projects</a> or the
   <a href="/docs">documentation</a> I wrote. At least that's what I consider most important.</p>

<p>You can also find me in other places:</p>
<ul>
  <li> Github: <a href="http://github.com/dmbaturin">github.com/dmbaturin</a> </li>
  <li> Blog: <a href="http://stuff.baturin.org">stuff.baturin.org</a> </li>
  <li> Twitter: <a href="http://twitter.com/dmbaturin">@dmbaturin</a> </li>
  <li> dmbaturin on <a href="http://freenode.net">Freenode</a> and <a href="http://esper.net">Esper</a>
       IRC networks.</li>
</ul>

<p>You can contact me by email &lt;daniil (at) baturin (dot) org&gt;
(use <a href="http://pool.sks-keyservers.net:11371/pks/lookup?op=vindex&amp;search=0x4726DF9511E0AF1F">PGP key</a>
if you wish).</p>

<hr />

<p>Everything you see here is distributed under the terms of the
   <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution</a> license, unless otherwise specified.</p>

<p> <strong>Note:</strong>I use self-hosted <a href="http://piwik.org">Piwik</a> for statistics to satisfy my
  curiosity regarding the visitors. It doesn't store complete IP addresses and respects the Do Not Track header,
  so if you have a problem with it, just enable DNT and you should be fine.</p>
