<h1>Publications and talks</h1>

<h2>Computer magazine articles</h2>

<p>Articles in the Hacker Magazine (in Russian): <a href="https://xakep.ru/author/dmbaturin/">xakep.ru/author/dmbaturin</a>.</p>

<p>
  <strong>Simpler firewalls with IPset</strong>, in <em><a href="http://www.linuxformat.com/archives?issue=193">Linux Format issue 193</a></em>, January 2015 <br />
  Available to subscribers. Walks the reader through configuration of a very underappreciated tool, IPset, which allows using groups of
  hosts, networks, and ports in iptables rules.
</p>

<h2>Conference talks</h2>

<p>
  <strong>Text parsing with Python and PLY</strong>, in <em>proceedings of <a href="http://lvee.org">LVEE 2014</a></em>,
  August 22-24 2014, Minsk, Belarus.
</p>
<ul>
  <li>Abstract: <a href="http://lvee.org/en/abstracts/122">lvee.org/en/abstracts/122</a> </li>
  <li>Slides: <a href="http://www.slideshare.net/dmbaturin/dmbaturin-lvee2014?qid=9d925f33-b7d0-4d5e-9caf-0291307e4017&v=qf1&b=&from_search=10">
      on slideshare</a>.</li>
  <li>Example code: <a href="https://github.com/dmbaturin/ply-example">github.com/dmbaturin/ply-example</a> </li>
</ul>
<p>Wanted to show people how to use a YACC with a language other than C.</p>

<h2>Elsewhere on the web</h2>

<ul>
  <li>Most of the posts in the <a href="https://blog.vyos.net">VyOS blog</a>.
  <li>An <a href="https://learnxinyminutes.com/docs/ocaml/">OCaml tutorial</a> on learnxinyminutes.com</li>
</ul>
