{% set date 2019 June 01 %}

<h1>Choosing woodwind instruments</h1>

<p>
If you are a parent whose kid wants to get flute/clarinet/saxophone lessons,
or an adult who decided to make a childhood dream finally come true, buying your first
instrument can be very confusing.
</p>
<p>
The best thing to do is usually to find a good teacher first and follow their advice.
But even then, you should better understand the reasoning behind their choice.
</p>

<h2>Instrument hierarchy</h2>

<p>
Generally, all instruments can be divided into these categories:
</p>
<ol>
  <li>Instruments by noname manufacturers</li>
  <li>Student instruments by reputable manufacturers</li>
  <li>Intermediate and professional instruments by reputable manufacturers</li>
</ol>

<p>
Student instruments by reputable manufacturers are the baseline reasonable instruments.
They are more or less in tune, don't sound too bad, and will last years with proper care.
You can be sure they will not limit your technique development. They are also reasonably safe
to buy online due to consistent quality control, but may still need adjustments to play at their best.
</p>
<p>
Above that, in the intermediate and professional range of those reputable manufacturers,
it gets better, but the cost of improvements gets higher with every step. It's safe to say that a
$500 instrument is five times better than a $100 one, but with a $1000 vs $5000 instruments,
the picture is much more complicated.
The best advice is probably
to develop enough technique and play as many different instruments as you can to be able
to judge for yourself. Else you may end up spending a lot of money for a wrong instrument.
</p>
<p>
At the opposite end, the very cheap instruments may have all kinds of design and manufacturing problems,
and aren't very durable. If your budget is really tight and renting is not an option, you may buy
them in person with careful assesment by someone with decent playing and maintenance experience.
Ordering them online is an incredibly bad idea unless you can easily return them.
</p>
<p>
One warning sign of noname instruments is unusual color, i.e. anything other than black for clarinets
and oboes, anything other than silver or gold for flutes and saxophones.
</p>

<h3>Reputable manufacturers</h3>

<p>
Reputable manufacturers include: Yamaha, Buffet Crampon, Leblanc, Selmer, Jupiter, Pearl Flutes.
That list is not exhaustive of course. You should note that some manufacturers may look reputable but
in fact are barely above the noname category.
</p>

<h2>Quality criteria</h2>

<ol>
  <li>Intonation</li>
  <li>Acoustic design</li>
  <li>Build and material quality</li>
  <li>Factory setup</li>
</ol>

<h3>Intonation</h3>

<p>
In case you don't know yet, wind instruments don't automatically play in tune when you
close the right holes. Your breathing, your lips, and even the position of your palate
and the back of your tongue can and will affect intonation.
</p>
<p>
The built-in intonation, determined by placing and size of the holes, has a huge impact
though. You will occasionally have to correct the tuning on the fly even with the best instrument in the world,
but bad instruments can make your life much harder. A really bad instrument can have tuning problems
you practically can't do anything about.
</p>
<p>
Cheap noname instruments are most likely to have serious problems. Decent student instruments
are more or less guaranteed to have a decent tuning, but may have weak spots here and there.
Professional instruments have to be tuned as precicely as our current technology allows.
</p>

<h3>Acoustic design</h3>

<p>
It's natural to expect a better instrument to have better tone.
The reality is rather complicated though.
</p>
<p>
The tone of woodwind instruments is a rather flexible thing. Sure, every instrument
has its built-in tonal concept, but different mouthpieces and reeds can make a big difference.
The player also has a very big impact. If you hand the same instrument to different players,
you will hear a different tone. Likewise, a decent player will sound more or less like themselves
on any instrument you give them.
</p>
<p>
As a beginner, you shouldn't care about the build-in tone much. What you should care about is
tone <em>evenness</em>.
</p>
<p>
The very cheap instruments are most likely to have notes that stick out as muffled, or stuffy,
or different from their surroundings in some way in general.
There may also be a noticeable difference between low and high notes.
</p>
<p>
Decent student instruments may still have those problems. Really even tone across all registers is a mark of
a professional instrument, it's difficult to achieve, and it's going to cost you a lot.
However, as a student, you are going to have more tone evenness problems due to your technique than the
instrument construction, so minor issues is not a big concern.
</p>

<h3>Build and material quality</h3>

<p>
If you want to make an instrument cheap, you have to take shortcuts. Using cheaper materials is one such
shortcut. Some shortcuts are much more problematic than other though.
</p>
<p>
Body material is not a big concern for reasons discussed <a href="#wood">below</a>. Your bigger concern
is the material the keys are made from.
</p>
<p>
Cheapest instruments often have keys made from laughably soft alloys that may bend simply from playing them,
and it doesn't take a particularly heavy-handed person. Bent keys is a recipe for disaster. The key hinges will
also wear out faster, and make the keywork wobbly. Repairing them may not be economically viable.
</p>
<p>
Decent instruments (student and professional alike) use better alloys that do not bend easily and will last much longer.
They also usually (but not always) use a better type of <a href="http://www.shwoodwind.co.uk/Glossary/Points.htm">screws</a>
that can be adjusted to compensate for wear.
</p>

<h3>Factory setup</h3>

<p>
Woodwind instruments are complex mechanical devices that require careful adjustment. Even a tiny leak may make it
much harder to play, or even completely unplayable. Manufacturing quality is a necessary but not a sufficient condition
for having an instrument that plays well, it also needs a proper setup. Pads should be installed at correct height and angles,
regulation corks and felts must be of correct thickness, and adjustment screws must be set properly.
</p>
<p>
Professional quality instruments are likely to have been play tested at the factory and have had their setup adjusted,
though it's not guaranteed. It's also not guaranteed that <em>you</em> will like that setup, for example, you may find it
too stiff.
</p>
<p>
Student instruments from reputable manufacturers usually come playable, but are more likely to need adjustments.
And the cheapest noname instruments can have any kinds of setup problems.
</p>
<p>
Generally, it's always a good idea to take a new instrument to a repairer and have it checked and adjusted.
If you are serious about woodwind playing, you should also consider learning how to do it yourself, but that's
another story.
</p>

<h2 id="wood">Wood vs plastic, nickel vs silver etc.</h2>
<p>
The <em>body</em> material is not really a big concern when it comes to tone. Professional instruments are often made from
expensive hardwoods and precious metals, but it has more to do with tradition and a touch of luxury than
anything else. The body is merely a container for vibrating air, and it was repeatedly proven that
in blind tests people cannot identify body material by sound. This is somewhat counterintuitive, so the myths persist.
</p>
<p>
This <a href="https://bretpimentel.com/does-material-affect-tone-quality-in-woodwind-instruments-why-scientists-and-musicians-just-cant-seem-to-agree/">article</a>
by Dr. Bret Pimentel is a good introduction and a source of references for further reading. A fun fact is that different manufacturers
often assign contradictory qualities to the same material, as Stephen Howard noted in his <a href="http://www.shwoodwind.co.uk/misc/myths_and_materials.htm">article</a>.
</p>
<p>
You may want take this <a href="https://www.theclarinet.net/History/metal-clarinet-test.html">wood vs metal clarinet test</a>
yourself.
</p>
<p>
The material myths are hard to disprove though, so even manufacturers that don't spread them still have to play along with them,
and professional quality instruments are made from expensive materials. As a rare exception, Buffet Crampon makes their
professional clarinets and oboes in wooden and synthetic versions. In any case, you should never assume that an instrument is
good just because it's made from african blackwood or silver rather than plastic or nickel. You should not assume anything at all
based on material alone.
</p>
<p>
What does matter is required maintenance and durability. Wooden instruments can be a very bad idea for complete beginners,
very young players, and people who want to play outside because wood can crack, and you need to be careful to wipe the instrument
thoroughly after playing, never play it until it warms up to the room temperature, and avoid abrupt temperature changes if you don't want it to crack.
And it still may crack regardless.
</p>
<p>
Plastic instruments don't have this problem. There are two kinds of plastic used for making clarinets and oboes: hard rubber (also called <a href="https://en.wikipedia.org/wiki/Ebonite">ebonite</a>,
which should not be confused with <a href="https://en.wikipedia.org/wiki/Ebony">ebony</a>) and <a href="https://en.wikipedia.org/wiki/Acrylonitrile_butadiene_styrene">ABS</a>.
The tonal difference between them is non-existent for reasons discussed above. One difference is that hard rubber often develops a greenish discoloration over time,
while ABS is practically eternal and also has a higher melting point.
</p>
<p>
Regarding metals used for making flute bodies and key plating, you should note that nickel does not tarnish under normal conditions and it's also
more durable than silver. Good luck finding a high quality instrument with nickel plating though, they are all plated with silver because it's cooler.
Also, &ldquo;nickel silver&rdquo; is a <a href="https://en.wikipedia.org/wiki/Nickel_silver">nickel alloy</a> that doesn't contain any silver.
</p>

<h2>Counterfeit instruments</h2>

<p>
Counterfeit instruments do exist. Sadly, if you are new to woodwinds, it may be very hard to spot the warning signs.
To avoid it, it may be better to order from specialized online retailers rather than marketplaces such as eBay and AliExpress,
or have someone experienced look at the listing.
</p>

<h2>Used instruments</h2>

<p>
Buying a used instruments can be a great way to save money, but the downside is that they may need extensive maintenance and repair.
You should always have an experienced person look at it before you buy it.
</p>
<p>
You should also note that very old instruments can be problematic, especially for beginners. Woodwinds are relatively young,
they only took their modern shape in the mid 19th century, and a huge progress in their manufacturing and design has been made
in the last 50 years. A woodwind instrument from the 1970's may be as good as new, one from the 1940's can be viable for an experienced
player who's ready to correct its tuning problems and put up with old keywork design, and an instrument from the 1920's is likely
unplayable by modern standards.
</p>
