<h1>Chords with common tones</h1>

<p>For those who love to substitute and reharmonize by numbers.</p>

<table>
  <tr>
    <th>Chord quality</th>
    <th>Substitution</th>
    <th>Common tones</th>
    <th>Example</th>
  </tr>
  <tr>
    <td colspan="4" class="table-caption"> <strong> Same tones in different order </strong> </td>
  </tr>
  <tr>
    <td> Suspended 4 </td>
    <td> Suspended 2 perfect fourth above </td>
    <td> 1 &rarr; 5, 4 &rarr; 1, 5 &rarr; 4</td>
    <td> Csus4 &rarr; Fsus2 (C F G &rarr; F G C) </td>
  </tr>
  <tr>
    <td> Major sixth chord </td>
    <td> Minor seventh chord with root major sixth above </td>
    <td> 1 &rarr; b3, 3 &rarr; 5, 5 &rarr; b7, 6 &rarr; 1 </td>
    <td> C6 &rarr; Am7 (C E G A &rarr; A C E G) </td>
  </tr>
  <tr>
    <td> Minor sixth chord </td>
    <td> Half-diminished seventh chord with root major sixth above </td>
    <td> 1 &rarr; b3, b3 &rarr; b5, 5 &rarr; b7, 6 &rarr; 1 </td>
    <td> Cm6 &rarr; Am7b5 (C Eb G A &rarr; A C Eb G) </td>
  </tr>
  <tr>
    <td colspan="4" class="table-caption"> <strong> Three common tones </strong> </td>
  </tr>
  <tr>
    <td> Dominant seventh </td>
    <td> Diminished seventh with root minor second above </td>
    <td> 3 &rarr; b3, 5 &rarr; b5, b7 &rarr; bb7</td>
    <td> C7 &rarr; C#dim7 (C E G Bb &rarr; C# E G Bb) </td>
  </tr>
  <tr>
    <td> Minor seventh </td>
    <td> Half-diminished seventh with root minor third below </td>
    <td> 1 &rarr; b3, b3 &rarr; 5, 5 &rarr; b7</td>
    <td> Fm7 &rarr; Dm7b5 (F Ab C Eb &rarr; D F Ab C) </td>
  </tr>
  <tr>
    <td> Major seventh </td>
    <td> Minor seventh with root major sixth above </td>
    <td> 1 &rarr; b3, 3 &rarr; 5, 5 &rarr; b7 </td>
    <td> Cmaj7 &rarr; Am7 (C E G B &rarr; A C E G) </td>
  </tr>
  <tr>
    <td> Major seventh </td>
    <td> Minor seventh with root major third above </td>
    <td> 3 &rarr; 1, 5 &rarr; b3, 7 &rarr; 5 </td>
    <td> Cmaj7 &rarr; Em7 (C E G B &rarr; E G B D) </td>
  </tr>
</table>

<time id="last-modified">2016-08-14</time>
