<h1>Clarinet reassembly</h1>

<p>
Woodwind instruments are pretty complex mechanical devices and even minor malfunctions in the
keywork can make them frustrating to play or completely unplayable.
</p>
<p>
There are few if any repairs you can do with an assembled instrument, so if you want to learn how to repair and tweak it,
you need to learn to disassemble and reassemble it first. Even if everything is otherwise in a good shape, instruments tend
to accumulate dirt over time, so you may want to learn it even if you don't plan to do any repairs.
</p>
<p>
If you doubt your ability to reassemble it correctly, the good thing is that everything is either unique size and shape
or interchangeable, so there is simply no way to do it wrong that will not be obviously wrong. Worst that can happen is that it will take you
multiple attempts to get it right. Clarinets also have only one adjustment screw (in the A key) so as long as you don't
tear the regulation corks off the keys, the keywork shouldn't go out of adjustment after reassembly.
</p>
<p>
The goal of this tutorial is to provide the correct assembly order in case you get stuck.
</p>

<h2>Before you begin</h2>

<p>
Make sure you understand how the mechanism works first. Once you do, the rest is just a matter of practice.
The best way to learn it is to move every key and see what else moves with it.
</p>
<p>
The only tools you need to reassembly is a flat screwdriver and some tool to manipulate the needle springs with.
The canonical tool is the spring hook. I often use forceps with serrated tips that I got from a medical supplies store.
In an emergency, you can manipulate them with a screwdriver, but it's tricky and annoying.
</p>
<p>Here's <a href="http://www.shwoodwind.co.uk/HandyHints/Springhook.htm">an article</a> on making your own spring hooks.</p>


<h2>The upper joint</h2>

<p>
The upper joint is somewhat prone to issues with dirt accumulating in tone holes, due to smaller tone holes.
It also has fewer parts and dependencies between keys are simpler so it's easier to reassemble.
</p>

<h3>Key dependencies</h3>

<p>
The following keys have no dependencies: the Ab key, the middle finger ring, the left sliver key, the side Eb key,
the register key.
</p>

<h3>Disassembly order</h3>

<ol>
  <li>Remove the Ab key.</li>
  <li>Remove the A key.</li>
  <li>Remove the middle finger ring.</li>
  <li>Remove the C#/G# key.</li>
  <li>Remove the side Eb/Bb key.</li>
  <li>Remove the side F# key.</li>
  <li>Remove the first trill key.</li>
  <li>Remove the second trill key.</li>
  <li>Remove the index finger ring.</li>
  <li>Remove the thumb ring.</li>
</ol>

<p>The register key can be easily removed even with all other keys still in place, so it doesn't matter when to remove it.</p>

<h2>The lower joint</h2>

<p>Disassemble the joint in the following order:</p>

<ol>
  <li>Remove the right F/C and Ab keys (they share the same rod screw).</li>
  <li>Remove the right E/B key.</li>
  <li>Remove the right F#/C# key.</li>
  <li>Remove the left F#/C# key.</li>
  <li>Remove the left E/B key.</li>
  <li>Remove the right F/C key.
  <li>Remove the ring keys. This allows you access to the right sliver key.</li>
  <li>Remove the right sliver key.</li>
</ol>

<h2>Reassembly</h2>

<p>
Put the keys back on in reverse order. Remember that some of the springs will be obscured by their own keys or some
other keys so they need to be engaged before you install the key.
</p>

<div id="revision">This page was last modified: 2017-01-28</div>
