{% set date 2019 May 20 %}

<h1>Fully notated pieces</h1>

<div id="generated-toc"></div>

<p>It's tempting to call it &ldquo;classical&rdquo;. I don't feel like it though. Simply being fully notated
   doesn't make it classical. &ldquo;Classical&rdquo; implies at least conformance with the common practice period
   traditions, or certain artistic merit, or both. Then again, a lot of contemporary classical music ignores
   the common practice period rules or breaks them on purpose. A lot of contemporary classical music isn't very good,
   to put it politely. On the other hand, a lot of common practice period music wasn't all that good either.</p>
<p>Still, I'm pretty sure if I call these exercises in composition &ldquo;classical music&rdquo;, real academic musicians
   will give me very odd looks. I'll stick with &ldquo;fully notated&rdquo; which is vague enough to cover everything
   and not offensive to anyone.</p>

<p>I notate all my music using MuseScore, which is free and open source. You can download it from <a href="https://musescore.org/">musescore.org</a>.</p>

<h3>Partita for a monophonic instrument solo no. 1 (A major)</h3>

<p>
A set of unaccompanied pieces in the baroque style. Two other movements are coming soon.
</p>
<p>
The range is chosen to be comfortably playable on the violin or any
of the common woodwinds as well as the trumpet.
</p>

<h4>Gavotte</h4>
<ul class="plain">
  <li> <a href="/music/fully-notated/op2019.1-1_gavotte.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op2019.1-1_gavotte.mid">MIDI</a> </li>
  <li> <a href="/music/fully-notated/op2019.1-1_gavotte.mscz">MuseScore file</a> </li>
</ul>

<h3>Album leaf 2018.12 (piano solo)</h3>

<p>
A winter holidays present for our music theory professor. Originally, &ldquo;album leaf&rdquo;
meant a short piece written as a gift for someone, in the era when handwritten poetry albums
were popular, and this piece is exactly that.
</p>

<ul class="plain">
  <li> <a href="/music/fully-notated/op_2018-02_album_leaf.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op_2018-02_album_leaf.mid">MIDI</a> </li>
  <li> <a href="/music/fully-notated/op_2018-02_album_leaf.mscz">MuseScore file</a> </li>
  <li> Date: December 2018 </li>
  <li> Original key: B-flat major </li>
</ul>

<h3>When I died, there was no one who could disprove it</h3>

<p>
A minimalist piece for a wind quartet and vibraphone that I wrote for Antonio Agostini during a contemporary music festival
where he offered a master class in composition, and I decided to give his methods a try.
Its title and intended program are taken from a single line poem by a psychedelic rock and punk
musician Egor Letov.
</p>
<p>
Somehow I lost the musescore file, but if anyone is willing to actually perform it and needs different
instrumentation, I can come up with something.
</p>

<ul class="plain">
  <li> <a href="/music/fully-notated/when_i_died.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/when_i_died.mid">MIDI</a> </li>
  <li> Date: November 2018 </li>
</ul>


<h3>Fake Folk Dance #2 (flute and piano)</h3>

<ul class="plain">
  <li> <a href="/music/fully-notated/op_2018-01_fake_folk_dance_2.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op_2018-01_fake_folk_dance_2.mid">MIDI</a> </li>
  <li> <a href="/music/fully-notated/op_2018-01_fake_folk_dance_2.mscz">MuseScore file</a> </li>
  <li> Date: January 2018 </li>
  <li> Original key: A major </li>
</ul>

<p>From an imaginary fake dance suite.</p>

<h3>Sarabande (violin and piano)</h3>

<ul class="plain">
  <li> <a href="/music/fully-notated/op2017-07_sarabande.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op2017-07_sarabande.mid">MIDI</a> </li>
  <li> <a href="/music/fully-notated/op2017-07_sarabande.mscz">MuseScore file</a> </li>
  <li> Date: December 2017 </li>
  <li> Original key: B minor </li>
</ul>

<p>
By the romantic era, the word &ldquo;sarabande&rdquo; lost all connections to a particular baroque dance.
Minor key, triple meter, let's call it a sarabande.
</p>

<h3>Fake Folk Dance</h3>

<ul class="plain">
  <li> <a href="/music/fully-notated/op2017-06_fake_folk_dance.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op2017-06_fake_folk_dance.mid">MIDI</a> </li>
  <li> <a href="/music/fully-notated/op2017-06_fake_folk_dance.mscz">MuseScore file</a> </li>
  <li> Date: August 2017 </li>
  <li> Original key: C minor </li>
</ul>

<p>More of an exercise in using the leading tone chord than anything.</p>

<h3>Waltz for a double bass solo</h3>

<ul class="plain">
  <li> <a href="/music/fully-notated/op2017-05_f_waltz.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op2017-05_f_waltz.mid">MIDI</a> </li>
  <li> <a href="/music/fully-notated/op2017-05_f_waltz.mscz">MuseScore file</a> </li>
  <li> Date: June 2017 </li>
  <li> Original key: F major </li>
</ul>

<p>I could not come up with any accompanying parts that I would really like, so I left it solo.</p>
<p>There are quite a few up strokes if you read it as written, adjust the bowings to taste.</p>

<h3>The Ballad of an Epic Fail</h3>

<ul class="plain">
  <li> <a href="/music/fully-notated/op2017-04_ballad_of_an_epic_fail.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op2017-04_ballad_of_an_epic_fail.mid">MIDI</a> </li>
  <li> <a href="/music/fully-notated/op2017-04_ballad_of_an_epic_fail.mscz">MuseScore file</a> </li>
  <li>Date: May 2017</li>
  <li>Original key: A minor</li>
</ul>

<p>It would make a good fantasy RPG theme I suppose, even though I didn't set out to make one.</p>


<h3>Rhythm Changes Prelude</h3>

<ul class="plain">
  <li> <a href="/music/fully-notated/op2017-03_rhythm_changes_prelude.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op2017-03_rhythm_changes_prelude.mid">MIDI</a> </li>
  <li> <a href="/music/fully-notated/op2017-03_rhythm_changes_prelude.mscz">MuseScore file</a> </li>
  <li>Date: April 2017</li>
  <li>Original key: C major</li>
</ul>

<p>
The harmony of George Gershwin's song &ldquo;I've Got Rhythm&rdquo; is immensely popular with jazz composers,
and served as a basis for numerous compositions such as Charlie Parker's &ldquo;Confirmation&rdquo;.
</p>
<p>
I thought it would be fun to write a classical period style composition based on the same chord progression,
for me it was also an exercise in writing Alberti bass. The main challenge for me was to connect the B section chords
smoothly as it consists entirely of secondary dominants (ragtime progression) and doesn't have obvious resolutions.
</p>

<h3>Awkward Waltz for Ann</h3>

<ul class="plain">
  <li> <a href="/music/fully-notated/op2017-02_awkward_waltz_for_ann.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op2017-02_awkward_waltz_for_ann.mid">MIDI</a> </li>
  <li> <a href="/music/fully-notated/op2017-02_awkward_waltz_for_ann.mscz">MuseScore file</a> </li>
  <li>Date: March 2017</li>
  <li>Original key: E minor</li>
</ul>

<p>The initial idea was to descend from the I to the V by major seconds. Funnily enough,
   later my friend pointed me to a very dissimilar song with similar harmonic idea, &ldquo;Stray Cat Strut&rdquo; by Brian Setzer.</p>
<p>The other idea was to write a piece that can be viewed as a jazz piece with an overly elaborate intro, or a fully notated piece with
   improvised sections. Something of a third stream perhaps.</p>
<p>The dedication was added after writing, to make it a last moment gift. Ann is cool, she plays double bass.</p>


<h3>Trivial Prelude</h3>

<ul class="plain">
  <li> <a href="/music/fully-notated/op_2017-01_trivial_prelude.pdf">PDF</a> </li>
  <li> <a href="/music/fully-notated/op_2017-01_trivial_prelude.mscz">MuseScore file</a> </li>
  <li>Date: January 2017</li>
  <li>Original key: B minor</li>
</ul>

<p>An example of constrained writing. There was a guy who wrote a book of scifi short stories
   and he wanted to include some &ldquo;theme music&rdquo; in it, encoded in ASCII (e.g. <a href="https://en.wikipedia.org/wiki/ABC_notation">ABC notation</a>)
   as a nod to early personal computer magazines and type-in BASIC programs they published. He ultimately scrapped the plan though.</p>
<p>It was a fun project nonetheless. Due to the limitations of the medium, it had to be short and rhythmically trivial.
   I tried to convey the sense of emptiness and uncertainty, in line with the mood of the stories.</p>
