{% set date 2017 January 28 %}

<h1>Music</h1>

<div id="generated-toc"></div>

<h2>Music I wrote and/or recorded</h2>

<h3>Scores</h3>

<ul>
  <li> <a href="/music/leadsheets">Jazz tunes (leadsheets)</a> </li>
</ul>

<p>I don't keep recordings of those public because my skills are still seriously lacking
   and I can't make anything worthy of public release. Believe me, you can play or imagine them
   better than I possibly could.</p>

<h3> Notes and tutorials </h3>

<ul>
  <li> <a href="/music/chord-substitutions">Chords with common tones</a> </li>
</ul>
