<h1>Music</h1>

<div id="generated-toc"></div>

<h2>Compositions, transcriptions, arrangements</h2>

<h3>Scores</h3>

<ul>
  <li> <a href="/music/leadsheets">Jazz tunes (leadsheets)</a> </li>
  <li> <a href="/music/fully-notated">Fully notated pieces</a> </li>
  <li> <a href="/music/transcriptions">Transcriptions, adaptations, arrangements etc.</a> </li>
</ul>

<h2>Notes and tutorials</h2>

<h3>Music theory</h3>

<ul>
  <li> <a href="/music/chord-substitutions">Chords with common tones</a> </li>
</ul>

<h3>Woodwind instrument maintenance and repair</h3>
<ul>
  <li> <a href="/music/clarinet-reassembly">Reassembling the clarinet keywork</a> </li>
</ul>

