{% set date 2017 January 02 %}

<h1>Music</h1>

<div id="generated-toc"></div>

<h2>Music I wrote and/or recorded</h2>

<h3>Scores</h3>

<ul>
  <li> <a href="/music/leadsheets">Jazz tunes (leadsheets)</a> </li>
</ul>

<h3>Recordings</h3>

<ul>
  <li>Bandcamp (&ldquo;release&rdquo; recordings only): <a href="http://dmbaturin.bandcamp.com">dmbaturin.bandcamp.com</a> </li>
  <li>Soundcloud (anything goes): <a href="https://soundcloud.com/dmbaturin">soundcloud.com/dmbaturin</a> </li>
</ul>

<p> <strong>Note:</strong> I'm still to get my old skills back even. These recordings sound amateurish at best,
    do not expect anything impressive or even just really listenable. <strong>They are as bad as it can get, so if you want
    something to listen to rather than to criticize and give suggestions, don't bother. You have been warned.</strong></p>

<h3> Notes and tutorials </h3>

<ul>
  <li> <a href="/music/chord-substitutions">Chords with common tones</a> </li>
</ul>


<p>And if anyone cares...</p>

<h2>Gear</h2>

<p>I have a taste for minimally viable gear, that is, the cheapest thing that actually works.</p>
<p>The electric guitar is an Epiphone LP-100. It could have shielded humbuckers, but otherwise
   it's a perfectly good guitar for its price, makes a good archtop substitute. The next option down
   the price range, LP Special II, has obvious cheap guitar feel to it, and the next option up
   costs twice as much, so I settled for this one, for now.</p>
<p>The clarinet is a Buffet B12, with default mouthpiece, for now. Plastic pins in the lever keys bother me a bit,
   and the case has barely enough space for the paraphernalia, but it feels and plays well.
   So far it lives up to its status of one of the most popular student clarinets, though I'm not nearly
   good enough at it to really compare it to anything.</p>

<h2>The story</h2>

<p>There must be a story here, right? There is always some it seems.</p>
<p>As a teen, I learnt some guitar on the street. Then I went to study classical guitar in school
   (and lived to tell the tale). With that indifferent guitar instructor I've got, I would be better off
   just practicing on my own, and I would call it a bad experience if it wasn't for the music theory
   instructor. She actually cared and she taught us a lot about the ways music works. She was also
   a cool singer and a sweet person generally.</p>
<p>For various reasons, around 2007 I stopped performing in public, and around 2009 I stopped playing
   altogether, and haven't returned to this idea until 2015, when my old idea to finally learn to play jazz
   made me take up the instrument again.</p>
<p>Oddly, what suffered most from that overly long break is my sense of time. But, well, everything suffered
   to varying degrees, and I'm still to regain it.</p>
<p>My interests lie mostly in swing and bebop/hard bop varieties of jazz and renaissance and baroque music.</p>
