{% set date 2016 September 02 %}

<div id="generated-toc"></div>

<p>All tunes I completed so far, in reverse chronological order.</p>
<p>Everything licensed under CC-BY unless otherwise specified,
   you can freely arrange and record them and do anything
   you want with the recordings, as long as you credit me as the composer.</p>
<p>If you do record them, I'll be glad if you share the recording with me, though you don't have to.</p>

<p>Keys are mentioned just for context, I place no particular importance on them (definitely not the
   &ldquo;<a href="http://www.wmich.edu/mus-theo/courses/keys.html">Eb major is the key of love and devotion</a>&rdquo; kind of importance),
   usually it's just where my fingers fall.</p>

<h3>Silly Dream</h3>

<ul class="plain">
  <li> <a href="/music/leadsheets/Silly_Dream.mcsz">MuseScore file</a> </li>
  <li> <a href="/music/leadsheets/Silly_Dream.pdf">PDF</a> </li>
  <li>Date: August 2016</li>
  <li>Original key: B minor</li>
</ul>

<p>I've had an idea to make something with repeated minor VI I motion.
   Then I wrote this melody independently of that idea and realized that
   it mostly fits, except it features the dominant over the I prominetly,
   which I found fun.</p>
<p>The rest has been padded with minor ii V I's and the &ldquo;industry standard&rdquo;
   major ii V I and minor ii V I connected through IV move.
   The V<sup>7alt</sup> of the original minor key at the end of A section that makes the transition to the B section's
   relative major sound better was kindly suggested by Mike Holstein, I doubt I'd come up with it myself.</p>
<p>You can think that the title refers to the dream to become a better composer/improvisor.</p>

<h3>Indirect Kiss</h3>

<ul class="plain">
  <li> <a href="/music/leadsheets/Indirect_Kiss.mcsz">MuseScore file</a> </li>
  <li> <a href="/music/leadsheets/Indirect_Kiss.pdf">PDF</a> </li>
  <li>Date: August 2016</li>
  <li>Original key: C major</li>
</ul>

<p>This tune turned out quite silly, and was given a matching name.</p>
<p>Pretty standard I vi ii V I progression, slightly spiced up with IV's
   and some Bb<sup>maj7</sup> chords whose function in C major context
   I can't determine, but I like how they sound there.</p>
<p>I quite like the C to Bb motion that appears throughout, though I was not
   very successful at exploring it in my solos so far.</p>
<p>Thanks to Stefaan Himpe for suggestions regarding the harmony.</p>

<h3>Hiding The Obvious</h3>

<ul class="plain">
  <li> <a href="/music/leadsheets/Hiding_The_Obvious.mcsz">MuseScore file</a> </li>
  <li> <a href="/music/leadsheets/Hiding_The_Obvious.pdf">PDF</a> </li>
  <li>Date: May 2016</li>
  <li>Original key: C major</li>
</ul>

<p>Twelve bar blues, slightly reharmonized, with excessive amount of flat 6ths.
   Dedicated to certain girl with great ears and amazing musical memory.</p>

<h3>Mojito Bay</h3>

<ul class="plain">
  <li> <a href="/music/leadsheets/Mojito_Bay.mcsz">MuseScore file</a> </li>
  <li> <a href="/music/leadsheets/Mojito_Bay.pdf">PDF</a> </li>
  <li>Date: February 2016</li>
  <li>Original key: C minor</li>
</ul>

<p>This was my first attempt to write anything after a <em>very</em> long
   break from music. Needless to say, it's showing here.</p>
<p>The idea was to see if I can make anything remotely listenable from a minor
   ii V I alone (it worked for the A sections of &ldquo;I've got you under my skin&rdquo;,
   right). Prominent B natural over the altered V is probably the only funny find
   in the whole thing.</p>
<p>I've had no idea what to name it and asked Mike Holstein to suggest something,
   and he invented this title. The fun part is that I have little idea what that
   mojito thing is, I quit drinking altogether long ago.</p>
