<h1>Misc</h1>

<p>Various things that don't fit anywhere else.</p>

<ul class="nav">
  <li class="nav"> <a href="/misc/quotes">Quotes</a> </li>
  <li class="nav"> <a href="/misc/software-reviews">&ldquo;Reviews&rdquo;</a> of historical operating systems and other software </li>
  <li class="nav"> <a href="/misc/wishlist">Wishlist</a> </li>
  <li class="nav"> <a href="/misc/morrowind-mods">Mods for The Elder Scrolls III: Morrowind</a> </li>
</ul>

<p>Things that have no justification for their existence but exist nonetheless:</p>
<ul class="nav">
  <li class="nav"> <a href="/misc/blank-page">Blank page</a> </li>
  <li class="nav"> <a href="/misc/web10">Web 1.0 memorial</a> </li>
  <li class="nav"> <a href="/misc/sysadmin-christmas-carol">Sysadmin Christmas carol</a> </li>
</ul>

