<h1>Quotes</h1>

<blockquote>
Our biggest mistake was using the scary term &ldquo;monad&rdquo; rather than &ldquo;warm fuzzy thing&rdquo;.
</blockquote>
<div class="quote-source">&mdash; Simon Peyton Jones</div>

<blockquote>
I remember being impressed with Ada because you could write an
infinite loop without a faked up condition.  The idea being that in Ada
the typical infinite loop would be normally be terminated by detonation.
</blockquote>
<div class="quote-source"> &mdash; Larry Wall
<span class="footnote" id="ada-loops">
This can give a wrong impression that you can't escape a loop in Ada.
You can, either with &ldquo;exit [when &lt;condition&gt;]&rdquo; statement
or by raising an exception. Otherwise it's true, &ldquo;loop ... end loop;&rdquo;
creates an infinite loop, finite loops are created by adding a condition before the
&ldquo;loop&rdquo; keyword.
</span>
</div>

<blockquote>
Ada language is a voice from thermonuclear hell, a curse to the humankind.
</blockquote>
<div class="quote-source"> &mdash; Melor Sturua
<span class="footnote" id="ada-izvestia">
This is from an <a href="http://www.orwell.ru/a_life/Melor_Sturua/russian/ms_01">article</a>
in a soviet newspaper that described the USA as an antiutopia.
The author compared it to Orwell's Newspeak as if it was a constructed language,
which suggests that he had little idea what a programming language is. Neither he knew that
Ada was used in the USSR too.
</span>
</div>

<blockquote>
Objects are state data with attached behavior; closures are behaviors with attached state data and without the overhead of classes.
</blockquote>
<div class="quote-source">&mdash; Peter Norvig</div>

<blockquote>
Given enough bugs, all eyes are shallow.
</blockquote>
<div class="quote-source">&mdash; Sad but true.</div>

<blockquote>
A programming language is low level when its programs require attention to the irrelevant. 
</blockquote>
<div class="quote-source">&mdash; Alan Perlis, Epigrams on Programming</div>

<blockquote>
Under no circumstances confuse the mesh with the interleave operator, except under confusing circumstances.
</blockquote>
<div class="quote-source">&mdash; D. Woods and J. Lyon, the INTERCAL reference manual</div>

<blockquote>
Programming languages should be designed not by piling feature on top of feature, but by removing the
weaknesses and restrictions that make additional features appear necessary.
</blockquote>
<div class="quote-source">&mdash; R5RS</div>

<blockquote>
Software tends to live too long: just good enough to discourage replacement, but slowly rotting away with more and more problems that are hard to fix.
</blockquote>
<div class="quote-source">&mdash; John Ousterhout</div>

<blockquote>
Within the Oceans of Great Risk were many Sun Worshippers, and they had wanted to excel, and make their words perfect, and do their jobs as easy as one-two-three.
</blockquote>
<div class="quote-source">&mdash; unknown
<span class="footnote" id="dosfish">
It comes from <a href="https://www.astro.umd.edu/~avondale/extra/Humor/ComputerHumor/PeaSea.html">this story</a>
which can be found on many websites often without attribution, and I really would like to know who the original
author is.
</span>
</div>

<blockquote>
I need privacy, not because my actions are questionable, but because your judgement and intentions are.
</blockquote>
<div class="quote-source">&mdash; unknown</div>

<blockquote>
If it hurts, do it more often.
</blockquote>
<div class="quote-source">&mdash; Martin Fowler</div>

<blockquote>
Live in the future, then build what's missing. 
</blockquote>
<div class="quote-source">&mdash; Paul Graham</div>

<blockquote>
The future will be better tomorrow.
</blockquote>
<div class="quote-source">&mdash; Dan Quayle</div>

<hr />


<div id="footnotes">
</div>
