<h1>Web 1.0 memorial</h1>

<p>
Web 1.0 is gone for good, and deserves a memorial. A good memorial design should be centered around something that is truly gone.
What is truly gone, however? There are still plenty of pages with animated Flash banners that will make anyone remember animated GIFs fondly,
absurd backgrounds, crazy colors, messy markup and so on.
</p>
<p>
The once ubiqiotous &ldquo;Under construction&rdquo; sign appears to be truly gone though. There are still &ldquo;Coming soon&rdquo; placeholders,
permanent &ldquo;Beta&rdquo; websites/applications, and, of course, obviously incomplete pages, but the iconic sign is not seen anymore, and thus
truly belongs to the web 1.0 era.
</p>
<p>Due to lack of funding, the web 1.0 memorial page is still under construction.</p>

<div class="centered">
  <img src="/images/under-construction.png" alt="Construction road sign" />
</div>
