<h1>Wishlist</h1>

<p>If you have any of these and don't need it anymore, I'll be glad if you send it to me.
   I'm ready to cover the shipping costs.</p>

<ul>
  <li><a href="http://infolab.stanford.edu/~ullman/ialc.html">Introduction to Automata Theory, Languages, and Computation</a>
      by John Hopcroft and Jeff Ullman</li>
  <li> <a href="http://www.ccs.neu.edu/home/matthias/BTML/">The little MLer</a> by by Daniel P. Friedman and Matthias Felleisen</li>
  <li> <a href="https://mitpress.mit.edu/index.php?q=books/basic-category-theory-computer-scientists">Basic Category Theory for Computer Scientists</a>
       by Benjamin C. Pierce</li>
</ul> 
   
