<h1>Software reviews</h1>

<p>Software reviews, so to speak. Except the software is historical or uncommon.
   In other words, software you are unlikely to have seen, and probably unlikely to want to see.</p>

<ul class="nav">
  <li class="nav"> <a href="rh73">Red Hat Linux 7.3 (2002)</a> </li>
  <li class="nav"> <a href="unixware714">SCO UnixWare 7.14+ (2004-2013)</a> </li>
  <li class="nav"> <a href="lindows">Lindows 4.0 (2003)</a> </li>
</ul>

<h3>A note on copyrights</h3>

<p>I assume that screenshots of software inherit the copyright from that software.
   In case of non-free software, I believe distributing screenshots is fair use, as vieweing screenshots cannot replace using the
   software, and therefore cannot affect its value.</p>
<p>If you are a copyright holder and you think otherwise, please contact me.</p>
