<p>SCO (now Xinuos) is widely known for its attemtps to sue IBM over intellectual property
   allegedly transferred to Linux authors.</p>
<p>So, why not look at their own offerings? They have two seemingly distinct OS products,
   UnixWare and OpenServer. This time we'll look at UnixWare, which is apparently older and has
   distinctive old proprietary UNIX feel.</p>
<p>Installation image is available from their website, a 14 day trial license included.</p>
<p>UnixWare 7.1.4 is the latest release which is still sold by Xinuos, not a historical version.</p>

<p>Booting from the installation CD.</p>
<a href="/images/uw714/03_SCO_install_start.png"> <img src="/images/uw714/preview/03_SCO_install_start.png"/> </a>

<p>After accepting the license, we are told about a yearly subscription. I didn't bother to find out what it costs.</p>
<a href="/images/uw714/05_SCO_install_subscription.png"> <img src="/images/uw714/preview/05_SCO_install_subscription.png"/> </a>

<p>Yes, trial is what I want.</p>
<a href="/images/uw714/06_SCO_install_trial.png"> <img src="/images/uw714/preview/06_SCO_install_trial.png"/> </a>

<p>Does anyone even remember that Ethernet had different framing types?</p>
<a href="/images/uw714/07_SCO_install_ethernet_framing.png"> <img src="/images/uw714/preview/07_SCO_install_ethernet_framing.png"/> </a>

<p>Now watch the progress bar. Doesn't take too long.</p>
<a href="/images/uw714/09_SCO_install_progress.png"> <img src="/images/uw714/preview/09_SCO_install_progress.png"/> </a>

<p>Complete.</p>
<a href="/images/uw714/10_SCO_install_complete.png"> <img src="/images/uw714/preview/10_SCO_install_complete.png"/> </a>

<p>Login screen, now with Xinuos logo instead of SCO logo. In most other places SCO logos are intact though.</p>
<a href="/images/uw714/SCO_login_screen.png"> <img src="/images/uw714/preview/SCO_login_screen.png"/> </a>

<p>Every time you login, you are reminded of the license.</p>
<a href="/images/uw714/SCO_restricted_rights_screen.png"> <img src="/images/uw714/preview/SCO_restricted_rights_screen.png"/> </a>

<p>CDE desktop.</p>
<a href="/images/uw714/SCO_cde_desktop.png"> <img src="/images/uw714/preview/SCO_cde_desktop.png"/> </a>

<p>CDE's default terminal emulator, dterm. The default shell is ksh. No completion, no history.</p>
<a href="/images/uw714/SCO_cde_dterm_uname.png"> <img src="/images/uw714/preview/SCO_cde_dterm_uname.png"/> </a>

<p>I'm not sure if this happens only with generic VESA driver, but color rendering is odd. With default settings,
   if you start a non-Motif application, all Motif widgets and window decorations are displayed like this.</p>
<a href="/images/uw714/SCO_colors_for_applications.png"> <img src="/images/uw714/preview/SCO_colors_for_applications.png"/> </a>

<p>Color display is configurable (presence of this option makes me think this problem is not graphics card specific).</p>
<a href="/images/uw714/SCO_cde_color_settings.png"> <img src="/images/uw714/preview/SCO_cde_color_settings.png"/> </a>

<p>Most color for applications gives the most comfortable look. Although this is hardly a problem for a system that
   is usually run headless, Solaris and other systems that used CDE didn't have it.</p>
<a href="/images/uw714/SCO_most_colors_for_applications.png"> <img src="/images/uw714/preview/SCO_most_colors_for_applications.png"/> </a>

<p>Also, it's Mozilla 1.7.13, straight from 2005.</p>
<a href="/images/uw714/SCO_mozilla_1713.png"> <img src="/images/uw714/preview/SCO_mozilla_1713.png"/> </a>

<p>There's a graphical configuration utility.</p>
<a href="/images/uw714/SCO_scoadmin.png"> <img src="/images/uw714/preview/SCO_scoadmin.png"/> </a>

<p>A number of applets is available, e.g. this one for IPfilter.</p>
<a href="/images/uw714/SCO_ipfilter_gui.png"> <img src="/images/uw714/preview/SCO_ipfilter_gui.png"/> </a>

<p>Some of them fail to start. Maybe I did something wrong, not sure.</p>
<a href="/images/uw714/SCO_scoadmin_applet_fail.png"> <img src="/images/uw714/preview/SCO_scoadmin_applet_fail.png"/> </a>

<p>There's <a href="http://www.sco.com/skunkware/">Skunware</a>, a package collection.
   There is no easy way to setup packages over the Internet, so I've just downloaded some. Most packages are
   very outdated, maybe there are newer packages, but I couldn't find any.</p>

<p>There's a graphical package manager frontend, although it didn't see downloaded packages in my home dir.</p>
<a href="/images/uw714/SCO_package_manager.png"> <img src="/images/uw714/preview/SCO_package_manager.png"/> </a>

<p>Plain old pkgadd works though.</p>
<a href="/images/uw714/SCO_pkgadd.png"> <img src="/images/uw714/preview/SCO_pkgadd.png"/> </a>
