<h1>Web tools</h1>

<h3>Tunnel MTU and MSS calculator</h3>

<p>Here it is: <a href="/tools/encapcalc">encapsulation overhead calculator</a> </p>
<p>Allows you to quickly see the MTU and TCP MSS of tunnels with different combinations
   of encapsulated and encapsulating protocols (GRE, IPv4, Ethernet etc.).</p>

<h3>Random OBEY message generator</h3>

<p>Here it is: <a href="/tools/obey">OBEY</a> </p>

<p>If you watched John Carpenter's <a href="https://en.wikipedia.org/wiki/They_Live">They Live</a>
   movie, you know what it's all about. Features most or possibly all messages seen on
   billboards in the movie.</p>
