<h1>Web tools</h1>

<a href="/tools/encapcalc"><h3>encapcalc</h3></a>
<p>
Encapcalc is a visual MTU and MSS calculator. Click protocol buttons and see
how much they add to the frame and what the total MTU/MSS becomes.
</p>
<p>
Supports all common and many uncommon protocols from datalink to network layers:
ethernet, 802.1q VLAN, IP, IPv6, TCP, IPIP, GRE and more.
</p>
<p>
Available as a standalone app from <a href="https://github.com/dmbaturin/encapcalc">github.com/dmbaturin/encapcalc</a>,
it's a self-contained page that is easy to mirror.
</p>

<a href="/tools/bnfgen"><h3>BNFGen</h3></a>
<p>
BNFGen takes a BNF-like definition of a context-free grammar and generates a random text from it.
</p>
<p>
For rules with alternation, it allow you to choose how often each alternative is taken
so that you can tweak the grammar for longer and more realistic outputs.
</p>
<p>
This is just an online version of actual <a href="http://github.com/dmbaturin/bnfgen/">bnfgen</a>,
cross-compiled to JS with BuckleScript.
</p>

<a href="/tools/obey"><h3>OBEY</a></h3>
<p>
If you watched John Carpenter's <a href="https://en.wikipedia.org/wiki/They_Live">They Live</a>
movie, you know what it's all about. Features most or possibly all messages seen on
billboards in the movie.
</p>
<p>
For extra opression, the &ldquo;next message&rdquo; button is labeled &ldquo;OBEY&rdquo;
</p>
