<h1>Continuity</h1>

<p>
We've all seen the classic example from introductory logic courses: all humans are mortal, Socrates is a human, therefore, Socrates is mortal.
It sounds like a trivial exercise until you insert yourself into that predicate. &ldquo;I am mortal&rdquo; is some serious motivation to think how
this fact affects your life and the lives of people around you.
</p>
<p>
While I hope that I will be able to maintain my own stuff for quite a while, I'm well aware of my own mortality and of the fact that death of
one person always affects others in complex ways. They need to dispose of the corpse at the very least (while we are at it, I would like to
donate mine to a research or educational institution&mdash;better make it an asset than a liability). There are also many ways to become permanently unable
to maintain anything while still being technically alive, for various definitions of &ldquo;alive&rdquo;.
</p>
<p>
Of course, it's not me who gets to decide which of the things I made in my life remain relevant in one, five, or a hundred years after my death.
I would like my projects including websites to outlive me, both because one of my main reasons for building them is to share the tools
and information that may help other people, and because I'm just as vain as everyone else.
</p>

<h2>What I would like to be done if I'm dead (or otherwise permanently incapacitated)</h2>

<p>
I don't feel a need to burden anyone with the role of a virtual executor since I all projects I want to be public are already
public on the web, complete with their build scripts. Alexander Norman (xh at xh dot se) can easily gain root access to the server
because he hosts it (at the time of writing), so if anything needs to be done on the server he's the one to ask.
</p>
<p>
Since maintaining my domain indefinitely is impractical, and it's not even clear how its transfer can be arranged if I'm no longer able
to manage the account, I suppose websites will have to be moved to another place. Preferrably somewhere that is low maintenance and low or no cost,
such as github pages or similar, though I'd be just as fine with having it hosted on someone's personal server if they want to do it.
</p>
<p>If setting up &ldquo;301 Moved permanently&rdquo; redirects to the new location is feasible, that would be nice.</p>
<p>Add some note to the main page to make the new status of the website clear and explain what happened.</p>

<hr />

<p>
Since the content of the websites is published under free culture licenses, there's no ethical problem with modifying it.</p>
<p>
If you want to maintain any of the self-contained parts such as the <a href="/docs/iproute2">iproute2 manual</a>, it's perfectly
ok to make a fork of it and keep the updated version at a new location.
</p>

<time id="last-modified">2018-03-21</time>
