<h1>Personal information</h1>

<p>You can read my <a href="/personal/cv">CV</a> if you want.</p>

<p>If you want to let me login somewhere, here's my <a href="/files/dmbaturin_ssh_key.txt">SSH public key</a>.</p>

<p>If you have a good reason to believe that I'm dead or something, read the <a href="/personal/continuity">continuity</a> page.</p>

<h2>Less serious side</h2>
<ul class="nav">
  <li> <a href="/personal/facts/">Random facts and opinions</a> </li>
  <li> <a href="/personal/site-history">History of this home page</a> </li>
  <li> <a href="/personal/screenshots">Desktop screenshots</a> </li>
</ul>
