{% set date 2018 April 09 %}

<h1>Personal information</h1>

<p>You can read my <a href="/personal/cv">CV</a> if you want.</p>

<p>If you want to let me login somewhere, here's my <a href="/files/dmbaturin_id_rsa_pub.txt">SSH public key</a>.</p>

<p>If you have a good reason to believe that I'm dead or something, read the <a href="/personal/continuity">continuity</a> page.</p>

<h2>Publications and talks</h2>

<p>
  <strong>Simpler firewalls with IPset</strong>, in <em><a href="http://www.linuxformat.com/archives?issue=193">Linux Format issue 193</a></em>, January 2015 <br />
  Available to subscribers. Walks the reader through configuration of a very underappreciated tool, IPset, which allows using groups of
  hosts, networks, and ports in iptables rules.
</p>

<p>
  <strong>Text parsing with Python and PLY</strong>, in <em>proceedings of <a href="http://lvee.org">LVEE 2014</a></em>,
  August 22-24 2014, Minsk, Belarus.
</p>
<ul>
  <li>Abstract: <a href="http://lvee.org/en/abstracts/122">lvee.org/en/abstracts/122</a> </li>
  <li>Slides: <a href="http://www.slideshare.net/dmbaturin/dmbaturin-lvee2014?qid=9d925f33-b7d0-4d5e-9caf-0291307e4017&v=qf1&b=&from_search=10">
      on slideshare</a>.</li>
  <li>Example code: <a href="https://github.com/dmbaturin/ply-example">github.com/dmbaturin/ply-example</a> </li>
</ul>
<p>Wanted to show people how to use a YACC with a language other than C.</p>

<h2>Less serious side</h2>
<ul class="nav">
  <li> <a class="nav" href="/personal/facts/">Random facts and opinions</a> </li>
  <li> <a class="nav" href="/personal/site-history">History of this home page</a> </li>
  <li> <a class="nav" href="/personal/screenshots">Desktop screenshots</a> </li>
</ul>
