<h1>Desktop screenshots</h1>

<p>
Some people post photos of their cats, some post photos of their food. One might think they will eventually
combine the two and start posting photos of their cat's food, but I'm still to see it happen.
</p>
Meanwhile, I'll rather post my desktop screenshots. Desktop environment is something you normally don't think much
about, once it's setup anyway, but finding an old screenshot while trying to clean up the disk can be oddly nostalgic.
</p>


<a href="/images/screenshots/desktop/fluxcde_2009.png">
  <img src="/images/screenshots/desktop/fluxcde_2009.png" width="600px" alt="FluxBox screenshot with a few terminals demonstrating the FluxCDE theme" />
</a>

<p>
The oldest surviving screenshot I've ever found, it's from late 2009. It's actually a demonstration
of my <a href="https://www.box-look.org/p/1016906/">FluxCDE</a> theme for FluxBox.
</p>
<p>
I'm pretty sure the system at the time was OpenSuSE.
</p>

<hr />

<a href="/images/screenshots/desktop/squeeze_laptop_2011.png">
  <img src="/images/screenshots/desktop/squeeze_laptop_2011.png" width="600" alt="Stock Gnome2 screenshot" />
</a>

<p>
A setup from 2011 preserved in my account on an old laptop that my mother received in a process someone
aptly called &ldquo;reverse inheritance&rdquo;. The system was Debian Squeeze, which I installed so that I could
build Vyatta images right on my workstation at the time when I've been working at Vyatta inc.
</p>
<p>
I got tired of FluxBox for a reason I can't remember and switched to Gnome 2 at the time.
</p>

<hr />

<a href="/images/screenshots/desktop/hercules_20120825.png">
  <img src="/images/screenshots/desktop/hercules_20120825.png" width="600px" alt="Gnome2 screenshot with MVS in Hercules" />
</a>

<p>
Messing up with <a href="https://en.wikipedia.org/wiki/MVS">MVS</a> in <a href="http://www.hercules-390.org/">Hercules</a> in 2012.
The system is still Debian Squeeze.
</p>

<hr />

<a href="/images/screenshots/desktop/coq_20150119.png">
  <img src="/images/screenshots/desktop/coq_20150119.png" width="600px" alt="Screenshot of OpenBox and Coq">
</a>

<p>
Trying out the <a href="https://coq.inria.fr/">Coq</a> proof assistant in 2015. By that time I switched back to
an RPM-based distro (Fedora) from the aging Squeeze, and to OpenBox from the no longer developed Gnome 2.
</p>

<hr />

<a href="/images/screenshots/desktop/clean_desktop_2017.png">
  <img src="/images/screenshots/desktop/clean_desktop_2017.png" width="600px" alt="Screenshot of OpenBox">
</a>

<p>
Working on a tune in 2017.
</p>
<p>
That's my standard setup from 2016 to 2018, a Frankenstein desktop environment made from OpenBox, dmenu, and lxpanel without any other part
of LXDE. 
</p>

<hr />

<a href="/images/screenshots/desktop/clean_desktop_2018.png">
  <img src="/images/screenshots/desktop/clean_desktop_2018.png" width="600px" alt="Screenshot of Mate Desktop">
</a>

<p>
Debugging an IPsec issue in VyOS in 2018.</p>
<p>
 The OS is Fedora 28, and the franken-DE is no more, I got tired of maintaining it,
decided to give Mate Desktop another try after years, and found that its maintainers have done a great work making it even better
than GNOME2 used to be.
</p>

<div id="revision">This page was last modified: 2018-08-06</div>
