# A trivial subset of English.
# Generates one or more sentences.

# Generate up to ten sentences
<start> ::= <sentence>{1,10} ;

# It's fine to declare symbols out of order
# (<line_break> is defined at the end of the file).
<sentence> ::= <NP> <VP> "." <line_break>;

<NP> ::= <capitalized_article> " " <subject> " " ;

<VP> ::= <verb> " " <article> " " <object>;

# Make the indefinite article ("a") appear ten times more often than "the"
<article> ::= 10 "a" | "the";
<capitalized_article> ::= 10 "A" | "The" ;

<subject> ::=
    "customer" 
  | "system administrator"
  | "programmer"
;

<object> ::= "system" | "compiler" | "program";

<verb> ::= "used" | "installed" | "developed" ;

<line_break> ::= "\n"
