<p>I can't say I'm fond of writing documentation, but someone has to.</p>

<h3>iproute2 cheatsheet</h3>
<ul>
  <li> The page: <a href="/docs/iproute2">docs/iproute2</a> </li>
  <li> The git repo: <a href="https://github.com/dmbaturin/iproute2-cheatsheet">github.com/dmbaturin/iproute2-cheatsheet</a> </li>
</ul>

<h3>What I wish I knew when learning OCaml</h3>
<p>A collection of common OCaml questions and answers. Still work in progress.</p>
<ul>
  <li>Here: <a href="/docs/ocaml-faq">docs/ocaml-faq</a>
</ul>
<p>Maybe it will get its own repo some day, for now it's embedded in the website.</p>

<h3>Vyatta Bootcamp</h3>
<p>Vyatta quickstart guide in Russian, written back in 2011 for the russian community.</p>
<p>Kept for historical reasons, substantial part of it is not applicable to any of the extant
   Vyatta successors (Brocade vRouter, EdgeOS, and VyOS).
</p>
<p>On a side note, the term bootcamp plays pretty much the same role in Russian as
   Foo 101 in English. I'm not sure if it's because russian colleges don't use uniform course numbering
   or because russian society is inherently militarized.
</p>
<ul>
  <li> The file: <a href="/files/vyatta-bootcamp.pdf">vyatta-bootcamp.pdf</a> </li>
  <li> The git repo: <a href="https://github.com/dmbaturin/vyatta-bootcamp-ru">github.com/dmbaturin/vyatta-bootcamp-ru</a> </li>
</ul>
