{% set date to 2016 September 02 %}

<h1>Documentation</h1>

<div id="generated-toc"></div>

<p>I can't say I'm fond of writing documentation, but someone has to.</p>

<h3>iproute2 cheatsheet</h3>
<p>Probably the most complete guide to the &ldquo;ip&rdquo; part of iproute2 (the Linux network configuration tool)
   on the Internet.</p>
<p>The most visited page of this whole website, one of the first hits for &ldquo;iproute2 cheat sheet&rdquo;,
   &ldquo;iproute2 documentation&rdquo; and even just &ldquo;iproute2&rdquo; in many search engines,
   my formal justification for keeping a personal website in the age of Facebook and Instagram.</p>
<p>Through multiple small additions over a long time it grew to the size when it can make a good
   bedsheet print, and covers almost all iproute2 features (XFRM framework is a notable exception,
   though I hope I'll document it too eventually).</p>

<ul>
  <li> The page: <a href="/docs/iproute2">docs/iproute2</a> </li>
  <li> The git repo: <a href="https://github.com/dmbaturin/iproute2-cheatsheet">github.com/dmbaturin/iproute2-cheatsheet</a> </li>
</ul>

<h3>What I wish I knew when learning OCaml</h3>
<p>A collection of common OCaml questions and answers. Still work in progress.</p>
<ul>
  <li>Here: <a href="/docs/ocaml-faq">docs/ocaml-faq</a>
</ul>
<p>Maybe it will get its own repo some day, for now it's embedded in the website.</p>

<h3>Vyatta Bootcamp</h3>
<p>Vyatta quickstart guide in Russian, written back in 2011 for the russian community.</p>
<p>Kept for historical reasons, substantial part of it is not applicable to any of the extant
   Vyatta successors (Brocade vRouter, EdgeOS, and VyOS).
</p>
<p>On a side note, the term bootcamp plays pretty much the same role in Russian as
   Foo 101 in English. I'm not sure if it's because russian colleges don't use uniform course numbering
   or because russian society is inherently militarized.
</p>
<ul>
  <li> The file: <a href="/files/vyatta-bootcamp.pdf">vyatta-bootcamp.pdf</a> </li>
  <li> The git repo: <a href="https://github.com/dmbaturin/vyatta-bootcamp-ru">github.com/dmbaturin/vyatta-bootcamp-ru</a> </li>
</ul>

<h3>Undocumented EdgeOS commands, documented</h3>

<p><strong>Note:</strong> I'm no longer actively involved with EdgeOS, since Ubiquiti essentially turned it
   into yet another proprietary product. This was written back in 2013, and I have no idea if it's still relevant.</p>
<p>But if you are curios, here it is: <a href="/docs/edgeos-undocumented">undocumented EdgeOS commands</a> </p>
