<div> <a class="nav" href="/">Main page</a> </div>
<div> <a class="nav" href="/blog">Blog</a> </div>
<div> <a class="nav" href="/projects">Projects</a> </div>
<div> <a class="nav" href="/docs">Documentation</a> </div>
<div> <a class="nav" href="/tools">Web apps</a> </div>
<div> <a class="nav" href="/code">Code snippets</a> </div>
<div> <a class="nav" href="/publications">Publications</a> </div>
<div> <a class="nav" href="/notes">Notes</a> </div>
<div> <a class="nav" href="/music">Music</a> </div>
<div> <a class="nav" href="/pictures">Pictures</a> </div>
<div> <a class="nav" href="/misc">Misc</a> </div>
<div> <a class="nav" href="/personal">Personal</a></div>
