<li class="nav"> <a class="nav" href="/">Main page</a> </li>
<li class="nav"> <a class="nav" href="/projects">Projects</a> </li>
<li class="nav"> <a class="nav" href="/docs">Documentation</a> </li>
<li class="nav"> <a class="nav" href="/tools">Web tools</a> </li>
<li class="nav"> <a class="nav" href="/code">Code snippets</a> </li>
<li class="nav"> <a class="nav" href="/notes">Notes</a> </li>
<li class="nav"> <a class="nav" href="/music">Music</a> </li>
<li class="nav"> <a class="nav" href="/misc">Misc</a> </li>
<li class="nav"> <a class="nav" href="/personal">Personal</a> </li>


