<a class="nav" href="/">Main page</a>
<a class="nav" href="/projects">Projects</a>
<a class="nav" href="/docs">Documentation</a>
<a class="nav" href="/tools">Web tools</a>
<a class="nav" href="/code">Code snippets</a>
<a class="nav" href="/publications">Publications</a>
<a class="nav" href="/notes">Notes</a>
<a class="nav" href="/music">Music</a>
<a class="nav" href="/pictures">Pictures</a>
<a class="nav" href="/misc">Misc</a>
<a class="nav" href="/personal">Personal</a>


