<h1>Code snippets</h1>

<h2>Original programs</h2>

<p>Source code that doesn't deserve its own repositories.</p>

<p>Unless otherwise specified, these files are distributed under the terms of the
   <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0</a> license, which is
   equivalent to public domain.</p>

<ul class="nav">
  <li class="nav"> <a href="/code/japh">JAPHs and other obfuscated programs</a> </li>
  <li class="nav"> <a href="/code/oo-peano">Object-oriented Peano arithmetics in Python</a> </li>
  <li class="nav"> <a href="/code/mlton-overload">Function overloading in MLton</a> </li>
  <li class="nav"> <a href="/code/lwt-counter-server">Multi-client server example in OCaml with Lwt</a> </li>
</ul>

<h2>Code from papers and other sources</h2>

<p>These snippets are not original, they come from various papers and other sources. What I did is translation from
   one language to another, or translation from pseudocode to real sytnax, or possibly some other transformation
   that can make them easier to play with.</p>

<ul class="nav">
   <li class="nav"> Typed formatter from Olivier Danvy's <a href="http://www.brics.dk/RS/98/12/">Functional Unparsing</a>, translated to OCaml: <a href="/code/files/unparsing.ml">unparsing.ml</a> </li>
</ul>

